### ISSUE TITLE
Hard coded path

### ISSUE THREAD

**Issue by MashdorDev** [gabigorzoni/MiniProject1#10]
make sure that you change it from hard-coded path to relative path, from `c:/something/something` to `/folder/something/` so it will be able to run on other system as we deploy stuff online 

https://github.com/gabigorzoni/MiniProject1/blob/65c7b6de474355f769efd04606940851f6dfd507/back-end/server.js#L11-L12

**Comment by gabigorzoni** [comment]
I already updated my mini project
